name: NPCsTeamClaim
version: "1.0.0"
api-version: 1.13
description: "Claims villages and dunjeons."
author: oscardoras
main: org.bukkitplugin.npcsteamclaim.NPCsTeamClaimPlugin
depend: [Claim]
softdepend: [Team]