name: NPCsTeamClaim
version: "1.0.0"
api-version: 1.13
description: "Claims villages and dunjeons."
author: oscardoras
main: me.oscardoras.npcsteamclaim.NPCsTeamClaimPlugin
depend: [Claim]
softdepend: [Team]
permissions:
  npcsteamclaim:
    default: op
    children:
      npcsteamclaim.command: true
  npcsteamclaim.command:
    default: op
    children:
      npcsteamclaim.command.structure: true
  npcsteamclaim.command.structure:
    default: op